name: Code Formatting

on: [push, workflow_dispatch]

jobs:
  Code-Formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Prepare 'prettier' and 'prettier-plugin-sort-imports'
        run:  npm install -g prettier @trivago/prettier-plugin-sort-imports

      - name: Run 'prettier'
        run: prettier -w .

